### PR TITLE
Remove CommonJS support

### LINKED ISSUE #3349: Ava test() expression is not callable / has no call signatures
After updating Typescript from 5.5.4 to 5.6.3 i started to have an error 

```
error TS2349: This expression is not callable.
  Type 'typeof import("<full_path_to_project>/node_modules/ava/entrypoints/main")' has no call signatures.
``` 

Version of ava - 6.2.0
Version of Typescript - 5.6.3
Version of tsimp - 2.0.12

ava config

```
export default {
  files: ['tests/**/*.spec.ts'],
  extensions: {
    ts: 'module',
  },
  nodeArguments: ['--import=tsimp/import', '--no-warnings'],
  timeout: '2m',
  serial: true,
  concurrency: 1,
};
```

test example

```
import test from 'ava';
import type { ExecutionContext } from 'ava';

test('example', (t: ExecutionContext) => {
  t.is('8080', '8080');
});
```

 I expect not to have this warning from Typescript when using Ava.
 
 There was similar issue #2539, but it's closed and nothing from comments there helping me (first of all because I can not use require syntax).

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #3349

Breaking changes:

- Removes support for `ava.config.cjs` files
- Always uses `import()` to load test files and extra modules through the `require` configuration
- No longer includes `.cjs` extension in the defaults (so will not find `test.cjs` files)
- Removes the `commonjs` value in the `extensions` configuration
- [x] Update provider protocol to `ava-8` to reflect these changes (requires new `@ava/typescript`)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Ready

**Comment by novemberborn** [comment]
@sindresorhus looks good! I've tried to summarize the breaking changes in the PR description. Unfortunately this does impact the `@ava/typescript` provider protocol. I can ship a new version there that is compatible with AVA 7 and 8.

I've pushed a few further simplifications. I did add back support for configuring a `cjs` extension, but only with a `true` value. It's weird to specify `module`.

I wonder if, instead of mandating `module` for all other extensions we should just always mandate `true` values when extensions is given in object form. Or remove support for object form entirely. What do you think?

**Comment by sindresorhus** [comment]
> I wonder if, instead of mandating module for all other extensions we should just always mandate true values when extensions is given in object form. Or remove support for object form entirely. What do you think?

I would just remove support for object form.

**Comment by sindresorhus** [comment]
Your changes look good.

**Comment by novemberborn** [comment]
https://github.com/avajs/typescript/pull/63 is green, but I need to do a bunch of config to make it publish, so that's for another evening.

**Review by novemberborn — APPROVED** [review]
Just waiting for CI to pass and then this can be merged.

File: docs/06-configuration.md [hunk 1]
```diff
@@ -68,18 +68,18 @@ Provide the `typescript` option (and install [`@ava/typescript`](https://github.
```
Comment (xjx62xjv8s-droid) [inline docs/06-configuration.md:68]: ر

File: docs/06-configuration.md [hunk 2]
```diff
@@ -42,7 +42,7 @@ Arguments passed to the CLI will always take precedence over the CLI options con
 
 ## Options
```
Comment (xjx62xjv8s-droid) [inline docs/06-configuration.md:43]: ت
