### ISSUE TITLE
Ava test() expression is not callable / has no call signatures

### ISSUE THREAD

**Issue by zavoloklom** [avajs/ava#3349]
After updating Typescript from 5.5.4 to 5.6.3 i started to have an error 

```
error TS2349: This expression is not callable.
  Type 'typeof import("<full_path_to_project>/node_modules/ava/entrypoints/main")' has no call signatures.
``` 

Version of ava - 6.2.0
Version of Typescript - 5.6.3
Version of tsimp - 2.0.12

ava config

```
export default {
  files: ['tests/**/*.spec.ts'],
  extensions: {
    ts: 'module',
  },
  nodeArguments: ['--import=tsimp/import', '--no-warnings'],
  timeout: '2m',
  serial: true,
  concurrency: 1,
};
```

test example

```
import test from 'ava';
import type { ExecutionContext } from 'ava';

test('example', (t: ExecutionContext) => {
  t.is('8080', '8080');
});
```

 I expect not to have this warning from Typescript when using Ava.
 
 There was similar issue #2539, but it's closed and nothing from comments there helping me (first of all because I can not use require syntax).

**Comment by novemberborn** [comment]
Can you reproduce this outside of your project? With and without `tsimp/import`? Nothing would have changed in AVA so it suggests a problem elsewhere.

**Comment by KillyMXI** [comment]
Same issue.
Same versions of ava, TypeScript, tsimp.

Tests are still passing, but there are also these error messages in the output.
The one as reported above and the other:

```
error TS7006: Parameter 't' implicitly has an 'any' type.
```

**Comment by novemberborn** [comment]
@KillyMXI Can you reproduce this outside of your project? With and without tsimp/import? Nothing would have changed in AVA so it suggests a problem elsewhere.

**Comment by KillyMXI** [comment]
The issue reproduces if I bump `typescript` version to 5.6.3 or 5.7.2.

Trying to replace `tsimp`:

- `tsx` - can't make it work anymore;
- `ts-node` with `"--loader=ts-node/esm"` - it gives a warning about `--experimental-loader`, but no type errors.

Trying to roll back versions of `tsimp`:

- `ava` times out when using `tsimp` 2.0.11 and `typescript` 5.6.3 or 5.7.2 - only works with 5.5.4.

I guess `tsimp` introduced something in 2.0.12 that didn't require changes in `ava` as the client code, but caused this?

After facing the issue in one of my packages repo, I reproduced this in my playground repo with a single trivial test.
My repro branch: <https://github.com/mxxii/yet-another-typescript-package-template/tree/tsimp-issue-repro>
Test run log with the error messages: <https://github.com/mxxii/yet-another-typescript-package-template/actions/runs/12484026510/job/34840790959#step:5:10>

I've no idea how `ava` uses `tsimp`, so I'm not sure if this is enough to bring to their repo.

**Comment by novemberborn** [comment]
@KillyMXI 

> I've no idea how ava uses tsimp, so I'm not sure if this is enough to bring to their repo.

AVA doesn't, you are through your config. Raising an issue with them makes sense, I can help point out how AVA loads files etc if needed.

**Comment by novemberborn** [comment]
@cunneen There is a `default` property though, see these lines: https://github.com/avajs/ava/blob/024de32a15aba9fac4002aa8d3c2c076955f44f4/lib/create-chain.js#L104-L127

**Comment by zavoloklom** [comment]
Just wanted to share a workaround for this issue. You can suppress TypeScript compilation errors in AVA/TSIMP by setting the `TSIMP_DIAG` environment variable in your AVA config:

```
export default {
  ...
  environmentVariables: {
    TSIMP_DIAG: 'ignore',
  }
};
```

But this will [ignore all TypeScript diagnostics](https://github.com/tapjs/tsimp?tab=readme-ov-file#compilation-diagnostics).

**Comment by sindresorhus** [comment]
The issue here is that `entrypoints/main.d.cts` declares `export default test`, but `entrypoints/main.cjs` uses `module.exports = value` — the correct TypeScript declaration for that CJS pattern is `export = test`. This mismatch is a `FalseExportDefault` (confirmed by `@arethetypeswrong/cli`). TypeScript 5.6 added stricter detection of it, which tsimp now surfaces as `TS2349: This expression is not callable`.

The fix is to change `main.d.cts` to use `export =` with the standard `declare function` + `declare namespace` merge pattern.

That being said, I don't think this is worth fixing. I think it's better to just remove CommonJS support for tests. It's time.

**Comment by novemberborn** [comment]
@sindresorhus do you have time to implement that? `main` needs a major bump now anyway.

IIRC we can require the ESM entrypoint now, so there's no need to have the CJS entrypoint.

**Comment by sindresorhus** [comment]
Yup will do. Would be great with no other commits until then since it will touch a lot of files.

**Comment by novemberborn** [comment]
No need to get rid of all CJS, just change the entrypoint.

**Comment by sindresorhus** [comment]
I think it's better to do it fully and get everything cleaned up.

https://github.com/avajs/ava/pull/3437
